/**
 * Códigos de error personalizados para la aplicación.
 * Usados en facades y middlewares para consistencia.
 */
export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_ID: 'INVALID_ID',
  MISSING_FIELDS: 'MISSING_FIELDS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  // Errores de categorías
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  INVALID_PARENT_ID: 'INVALID_PARENT_ID',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CYCLIC_REFERENCE: 'CYCLIC_REFERENCE',
  NAME_ALREADY_EXISTS: 'NAME_ALREADY_EXISTS',
  // Errores de productos
  SETTINGS_NOT_FOUND: 'SETTINGS_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  BUSINESS_CONSTRAINT_FAILED: 'BUSINESS_CONSTRAINT_FAILED',
  // Errores de favoritos
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  // Errores de autenticación y autorización
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TERMS_NOT_ACCEPTED: 'TERMS_NOT_ACCEPTED',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  OAUTH_ACCOUNT_NO_PASSWORD: 'OAUTH_ACCOUNT_NO_PASSWORD',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  // Errores de contenido social
  SOCIAL_CONTENT_NOT_FOUND: 'SOCIAL_CONTENT_NOT_FOUND',
  MAX_ITEMS_REACHED: 'MAX_ITEMS_REACHED',
  // Errores de banners de promoción
  PROMO_BANNER_NOT_FOUND: 'PROMO_BANNER_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
